services:
  its-mobile-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: its-mobile-api
    restart: unless-stopped
    ports:
      - "32281:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
